baseURL = "https://jianny.net"
title = "JIANNY.386"
languageCode = "en"
DefaultContentLanguage = "en" # Change this to change the site's language
theme = "hugo.386"
preserveTaxonomyNames = true

[params]
    # The name to display as main title in the home page
    mainpagetitle = "All work no play makes Jian a dull boy"

    # The subtitle to display under the title in the home page
    mainpagesubtitle = "Learning as Fuel | Books as Compass | Open Source as Playground" 

    # The description of your website. It will be displayed in the home page
    mainpagedesc = "I believe in fostering open and honest sharing about various topics, and strive to provide valuable information and insights here. However, it's essential to understand that the content presented here is based on personal opinions and experiences and may not always be entirely accurate or objective."

    # The name to display in the copyright section in the footer
    copyrightname = "Jianny K"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    copyrighturl = ""

    # Show the "built on Hugo" disclaimer
    showhugo = true

    # Enable Emoji
    enableEmoji = true

    # Urls for social networks
    #facebook = "https://facebook.com"
    twitter = "https://twitter.com/jianny"
    linkedin = "https://linkedin.com/in/jianny"
    github = "https://github.com/jiannystein"
    #gitlab = "https://gitlab.com"

    # Enables or disables the loading animations. false activates them. Default is false.
    loadfastload = false

    # Sets the speed for the page loading effect. Default is 1.0.
    loadspeedfactor = 1.0

    # Enables or disables the second flyby cursor. Default is false.
    loadonepass = false

[params.copyright]
    name = "Wenjian K"

    # The url to use as link in the copyright name in the footer. Leave empty to use none.
    url = "https://www.credly.com/users/wenjian-khor/badges"

    # Text to go before copyright information
    prefix = "[Jianny](mailto://iam@jianny.net)"

    # Text to go between copyright and hugo disclaimer (if enabled)
    suffix = "With ❤ F/OSS community"

[menu]
  # This displays buttons in the navbar to access your contents
  [[menu.main]]
    identifier = "about" # An unique identifier for the button
    name = "Hugo"       # A display name for the button
    url = "/about/"      # The path to the content. It can lead to a single page (like here)
    weight = 30          # A number to order the buttons in the navbar

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"       # The path can lead to a content folder too.
    weight = 10

  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "https://docs.jianny.net"       # The path can lead to a content folder too.
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true